#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web1 54.237.207.77:80 check
        server web2 54.165.46.25:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
