#!/usr/bin/env bash
# This script displays Hi on 9th line, Best School every other line

count=1
while [ $count -le 10 ]; do
    echo Best School

    if [ $count -eq 9 ]
    then
	echo Hi
    fi
    let count+=1
done
