#!/usr/bin/env bash
# This script displays a counter for hours and minutes
# up to 12 hours

hour=0
minute=1
while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  while [ $minute -le 60 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
